In [73]:
import glob
import os
import pandas as pd

# 1. Create a single dataframe with the concatenation of all input csv files, adding a column called country

In [74]:
files = glob.glob("trendingYT/*videos.csv.zst")

dfs = []

for file in files:
    country = os.path.basename(file)[:2] 
    temp = pd.read_csv(file, compression="zstd", encoding="latin1")
    temp["country"] = country
    dfs.append(temp)

df = pd.concat(dfs, ignore_index=True)

df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. BeyoncÃ©,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. BeyoncÃ© ...,CA
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO â¶ \n\nSUBSCRIBE âº ...,CA
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,ð§: https://ad.gt/yt-perfect\nð°: https://...,CA

# 2. Extract all videos that have no tag.

In [75]:
no_tag_videos = df[
    (df["tags"].isna()) |
    (df["tags"].str.strip() == "") |
    (df["tags"] == "[none]")
]

no_tag_videos.head(15)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
41,JwboxqDylgg,17.14.11,Canada Soccer's Women's National Team v USA In...,Canada Soccer,17,2017-11-13T05:53:49.000Z,[none],36311,277,28,13,https://i.ytimg.com/vi/JwboxqDylgg/default.jpg,False,False,False,Canada Soccer's Women's National Team face riv...,CA
58,9B-q8h31Bpk,17.14.11,John Oliver Tackles Louis C.K. And Donald Trum...,TV Shows,22,2017-11-13T04:49:26.000Z,[none],106029,1270,101,181,https://i.ytimg.com/vi/9B-q8h31Bpk/default.jpg,False,False,False,"John Oliver on News, Politics ...",CA
78,1UE5Dq1rvUA,17.14.11,Taylor Swift Perform Ready For It - SNL,Ken Reactz,24,2017-11-12T05:18:02.000Z,[none],320964,8069,285,717,https://i.ytimg.com/vi/1UE5Dq1rvUA/default.jpg,False,False,False,Thanks for watching please subscribe and subsc...,CA
86,pmJQ4KwliX4,17.14.11,"LATEST Q POSTS: ROTHSCHILDS, HOUSE OF SAUD, lL...",James Munder,2,2017-11-12T21:25:40.000Z,[none],116820,1503,139,1066,https://i.ytimg.com/vi/pmJQ4KwliX4/default.jpg,False,False,False,https://pastebin.ca/3930472\n\nSupport My Chan...,CA
98,lHcXhBojpeQ,17.14.11,ä¸å±TVBè¦å¸ï¼ææ£10å¹´éæ¢ ç«¹é¦¬é«®å¦...,ææç¾æç,22,2017-11-12T12:49:50.000Z,[none],88061,47,58,17,https://i.ytimg.com/vi/lHcXhBojpeQ/default.jpg,False,False,False,NaN,CA
99,Yo84eqYwP98,17.14.11,"LA PIRE PARTIE ft Le Rire Jaune, Pierre Croce,...",Le Labo,24,2017-11-12T15:00:02.000Z,[none],432721,14053,576,1161,https://i.ytimg.com/vi/Yo84eqYwP98/default.jpg,False,False,False,Le jeu de sociÃ©tÃ©: https://goo.gl/hhG1Ta\n\n...,CA
115,_QHEPUKBn9g,17.14.11,âToo Alabama for Alabamaâ: SNL brutally mo...,MAXI POWER,23,2017-11-12T05:01:18.000Z,[none],20163,44,34,8,https://i.ytimg.com/vi/_QHEPUKBn9g/default.jpg,False,False,False,NaN,CA
120,SSLxfJ9rWeA,17.14.11,ç¡éèå°å°ç20åç·äººé¦æ¬¡æ­ç§ï¼ç...,nEWS 24-7,22,2017-11-12T11:31:55.000Z,[none],78178,65,64,24,https://i.ytimg.com/vi/SSLxfJ9rWeA/default.jpg,False,False,False,é»è¦åãäºä¸æµ®èãå³æ¯å ¶ææè³ã...,CA
123,1YhtkrC2t0c,17.14.11,New Eritrean film Dama (á³á) part 13 Shalo...,Shalom Entertainment,22,2017-11-11T17:21:54.000Z,[none],260199,4833,302,860,https://i.ytimg.com/vi/1YhtkrC2t0c/default.jpg,False,False,False,á°áá áá áªáµá® á«á¥á á³áá...,CA
131,O-_52G3aKVU,17.14.11,Taylor Swift SNL Call It What You Want on Satu...,vSpirit2,10,2017-11-12T09:23:20.000Z,[none],62915,1007,21,55,https://i.ytimg.com/vi/O-_52G3aKVU/default.jpg,False,False,False,"On Saturday Night Live November 11, 2017, Tayl...",CA
141,woJJNz1ZAV0,17.14.11,This Week in Stupid (12/11/2017),Sargon of Akkad,25,2017-11-12T11:19:28.000Z,[none],341134,18017,439,6073,https://i.ytimg.com/vi/woJJNz1ZAV0/default.jpg,False,False,False,Bend over for the Zuck. \n\nLive show! https:/...,CA
162,j9nCXKlZaSM,17.14.11,Alena TV -Tesfit Abraha - Dgul Hiyab - Part 4...,Alena TV,24,2017-11-12T21:09:54.000Z,[none],174130,4565,292,621,https://i.ytimg.com/vi/j9nCXKlZaSM/default.jpg,False,False,False,Alena TV -Tesfit Abraha - Dgul Hiyab - Part 4...,CA
163,L1fwxUV6GJE,17.14.11,Grey's Anatomy S10 Ep12 Jackson Stops The Wedding,Michelle 1,22,2014-09-03T21:24:07.000Z,[none],107331,206,5,8,https://i.ytimg.com/vi/L1fwxUV6GJE/default.jpg,False,False,False,Jackson stops April's Wedding scenes from Grey...,CA
165,OA0vhAKUD0g,17.14.11,Outlander S03E09 i'm melting with you'',Ella bell,1,2017-11-12T22:33:48.000Z,[none],32941,149,2,5,https://i.ytimg.com/vi/OA0vhAKUD0g/default.jpg,False,False,False,NaN,CA
175,w749rQf9gl8,17.14.11,è®¿è°æ¹é¿éï¼æ°¸ä¸æ¾å¼ââå¦ä½çå...,é­å¯¶åæ¿è«,25,2017-11-12T03:19:06.000Z,[none],64386,1639,86,472,https://i.ytimg.com/vi/w749rQf9gl8/default.jpg,False,False,False,æ¹å çå¨ç¹è¯å·æ®äºæ´²ä¹è¡åºç¡ä¸æ...,CA

# 3. For each channel, determine the total number of views

In [76]:
channel_views = (
    df
    .groupby("channel_title", as_index=False)["views"]
    .sum()
)
channel_views.sort_values(by="views", ascending=False).head(10)

              channel_title        views
4564    ChildishGambinoVEVO  11016766510
15536  Marvel Entertainment  10430605449
17726            NickyJamTV   9479859505
18466                 Ozuna   8623329509
28412               ibighit   8205572221
6689              DrakeVEVO   7637228580
2788              Bad Bunny   7124207494
2101       ArianaGrandeVevo   6202230488
28621      jypentertainment   5802822913
7047             Ed Sheeran   5775405574

# 4. Save all rows with disabled comments and disabled ratings, or that have video_error_or_removed in a new dataframe called excluded, and remove those rows from the original dataframe.

In [77]:
excluded = df[
    (df["comments_disabled"] == True) |
    (df["ratings_disabled"] == True) |
    (df["video_error_or_removed"] == True)
].copy()

In [78]:
df = df.drop(excluded.index).reset_index(drop=True)

In [79]:
print("Excluded rows:", excluded.shape[0])
print("Remaining rows in df:", df.shape[0])

Excluded rows: 13657
Remaining rows in df: 362285

In [80]:
excluded

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
67,amEZKmJQ4Io,17.14.11,Drako - Watch Me Do It [Official Video],babygranderecords,10,2017-10-23T19:38:36.000Z,"Drako|""Watch Me Do It""|""watch me""|""migos""|""dap...",25887,0,0,6,https://i.ytimg.com/vi/amEZKmJQ4Io/default.jpg,False,True,False,PURCHASE / STREAM WATCH ME DO IT https://fanli...,CA
70,TIvI07xLPnA,17.14.11,"The National for Sunday, November 12, 2017",The National,25,2017-11-13T03:06:10.000Z,"Canada|""CBC""|""CBC News""|""National""|""News""|""The...",13433,74,57,0,https://i.ytimg.com/vi/TIvI07xLPnA/default.jpg,True,False,False,"Welcome to The National, the flagship nightly ...",CA
82,Dgut-rlPVrk,17.14.11,Will Grace Davies make you love her? | Live Sh...,The X Factor UK,24,2017-11-12T19:59:14.000Z,"the x factor|""x factor""|""X factor UK""|""x facto...",261603,4276,2148,0,https://i.ytimg.com/vi/Dgut-rlPVrk/default.jpg,True,False,False,Visit the official site: http://itv.com/xfacto...,CA
173,H8IWLEtFt9A,17.14.11,IntÃ©grale - On n'est pas couchÃ© 11 novembre ...,On n'est pas couchÃ©,24,2017-11-12T01:44:07.000Z,"onpc|""on n'est pas couche""|""laurent ruquier""|""...",122282,0,0,0,https://i.ytimg.com/vi/H8IWLEtFt9A/default.jpg,True,True,False,IntÃ©grale - On n'est pas couchÃ© 11 novembre ...,CA
235,wDEA3rpYHnI,17.15.11,Marie-Louise Arsenault rÃ©plique Ã Denise Bom...,TV Classics,22,2017-11-13T01:26:37.000Z,Marie-Louise Arsenault qui rÃ©plique Ã Denise...,15800,88,0,0,https://i.ytimg.com/vi/wDEA3rpYHnI/default.jpg,True,False,False,Moment favori Ã la tÃ©lÃ© quÃ©bÃ©coise: Marie...,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375542,FchkqXEg0qs,18.13.06,Nintendo @ E3 2018: Day 1,Nintendo,20,2018-06-13T01:18:57.000Z,"nintendo|""play""|""play nintendo""|""game""|""gamepl...",3238183,61841,3708,0,https://i.ytimg.com/vi/FchkqXEg0qs/default.jpg,True,False,False,ESRB Rating: RATING PENDING to Teen. Rating Pe...,US
375617,J2m7EUwnqGg,18.13.06,iPhone X â Animoji: Taxi Driver â Apple,Apple,28,2018-06-04T04:00:00.000Z,"Apple|""iphone""|""iphone x""|""animoji""|""apple ani...",8903674,79182,31697,0,https://i.ytimg.com/vi/J2m7EUwnqGg/default.jpg,True,False,False,Animoji on iPhone X (feat. HYUKOH) Learn more ...,US
375624,lBbSzQXQknw,18.13.06,And the WINNER of Britainâs Got Talent 2018 ...,Britain's Got Talent,24,2018-06-03T21:11:48.000Z,"britain's got talent|""britains got talent""|""br...",4642895,53192,4312,0,https://i.ytimg.com/vi/lBbSzQXQknw/default.jpg,True,False,False,What an amazing show our acts put on tonight f...,US
375825,J2m7EUwnqGg,18.14.06,iPhone X â Animoji: Taxi Driver â Apple,Apple,28,2018-06-04T04:00:00.000Z,"Apple|""iphone""|""iphone x""|""animoji""|""apple ani...",8916546,79282,31716,0,https://i.ytimg.com/vi/J2m7EUwnqGg/default.jpg,True,False,False,Animoji on iPhone X (feat. HYUKOH) Learn more ...,US
375832,lBbSzQXQknw,18.14.06,And the WINNER of Britainâs Got Talent 2018 ...,Britain's Got Talent,24,2018-06-03T21:11:48.000Z,"britain's got talent|""britains got talent""|""br...",4678751,53469,4330,0,https://i.ytimg.com/vi/lBbSzQXQknw/default.jpg,True,False,False,What an amazing show our acts put on tonight f...,US

In [81]:
df

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. BeyoncÃ©,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. BeyoncÃ© ...,CA
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO â¶ \n\nSUBSCRIBE âº ...,CA
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,ð§: https://ad.gt/yt-perfect\nð°: https://...,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362280,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18T13:00:04.000Z,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals,US
362281,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US
362282,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18T17:34:22.000Z,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...,US
362283,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17T17:00:04.000Z,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...,US
362284,ooyjaVdt-jA,18.14.06,Official Call of DutyÂ®: Black Ops 4 âÂ Mult...,Call of Duty,20,2018-05-17T17:09:38.000Z,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US

# 5. Add a like_ratio column storing the ratio between the number of likes and of dislikes

In [82]:
df["like_ratio"] = df["likes"] / df["dislikes"].replace(0, pd.NA)
df[["likes", "dislikes", "like_ratio"]].head()

     likes  dislikes like_ratio
0   787425     43420  18.135076
1   127794      1688  75.707346
2   146035      5339    27.3525
3   132239      1989  66.485168
4  1634130     21082  77.513044

# 6. Cluster the publish time into 10-minute intervals (e.g. from 02:20 to 02:30)

In [83]:
df["publish_time"] = pd.to_datetime(df["publish_time"])
df["publish_interval"] = df["publish_time"].dt.floor("10min")
df[["publish_time", "publish_interval"]].head(10)

               publish_time          publish_interval
0 2017-11-10 17:00:03+00:00 2017-11-10 17:00:00+00:00
1 2017-11-13 17:00:00+00:00 2017-11-13 17:00:00+00:00
2 2017-11-12 19:05:24+00:00 2017-11-12 19:00:00+00:00
3 2017-11-12 18:01:41+00:00 2017-11-12 18:00:00+00:00
4 2017-11-09 11:04:14+00:00 2017-11-09 11:00:00+00:00
5 2017-11-13 07:37:51+00:00 2017-11-13 07:30:00+00:00
6 2017-11-12 23:52:13+00:00 2017-11-12 23:50:00+00:00
7 2017-11-13 17:13:01+00:00 2017-11-13 17:10:00+00:00
8 2017-11-12 20:19:24+00:00 2017-11-12 20:10:00+00:00
9 2017-11-10 14:10:46+00:00 2017-11-10 14:10:00+00:00

# 7. For each interval, determine the number of videos, average number of likes and of dislikes.

In [84]:
interval_stats = (
    df
    .groupby("publish_interval")
    .agg(
        video_count=("video_id", "count"),
        avg_likes=("likes", "mean"),
        avg_dislikes=("dislikes", "mean")
    )
    .reset_index()
)
interval_stats.sort_values("video_count", ascending=False).head(10)

               publish_interval  video_count      avg_likes  avg_dislikes
16226 2018-03-02 05:00:00+00:00          299  387412.846154  14168.571906
6437  2017-12-22 05:00:00+00:00          215  151799.818605   7418.488372
20901 2018-04-04 16:00:00+00:00          200  107900.060000   4649.640000
13174 2018-02-08 14:00:00+00:00          198  210740.333333  11246.484848
22576 2018-04-20 04:00:00+00:00          198  950468.757576  36147.166667
19127 2018-03-23 04:00:00+00:00          193  285309.544041   9018.740933
10325 2018-01-19 05:00:00+00:00          187  192095.679144  12868.379679
14170 2018-02-15 17:00:00+00:00          160   23370.631250   1182.756250
27501 2018-05-25 04:00:00+00:00          157  135612.127389  14947.178344
20120 2018-03-30 04:00:00+00:00          156  158389.256410   5646.666667

# 8. For each tag, determine the number of videos
### Notice that tags contains a string with several tags.

In [85]:
df["tag_list"] = df["tags"].str.split("|")


tags_exploded = df.explode("tag_list")
tags_exploded = tags_exploded[~tags_exploded["tag_list"].isin(["[none]", ""])]


tag_counts = tags_exploded.groupby("tag_list")["video_id"].count().reset_index()


tag_counts.columns = ["tag", "video_count"]


tag_counts = tag_counts.sort_values("video_count", ascending=False)


tag_counts.head(10)

                 tag  video_count
336366       "funny"        14834
277330      "comedy"        11900
12344         "2018"        10567
443876        "news"         5653
436000       "music"         5544
560940       "video"         5338
11560         "2017"         5334
363384       "humor"         4992
535014  "television"         4099
490026      "review"         4006

# 9. Find the tags with the largest number of videos

In [86]:
top_tags = tag_counts.sort_values("video_count", ascending=False)
top_tags.head(10)

                 tag  video_count
336366       "funny"        14834
277330      "comedy"        11900
12344         "2018"        10567
443876        "news"         5653
436000       "music"         5544
560940       "video"         5338
11560         "2017"         5334
363384       "humor"         4992
535014  "television"         4099
490026      "review"         4006

# 10. For each (tag, country) pair, compute average ratio likes/dislikes

In [87]:
tags_exploded_clean = tags_exploded[~tags_exploded["tag_list"].isin(["[none]", ""])]


tag_country_ratio = (
    tags_exploded_clean
    .groupby(["tag_list", "country"], as_index=False)["like_ratio"]
    .mean()
)

tag_country_ratio.columns = ["tag", "country", "avg_like_ratio"]

tag_country_ratio = tag_country_ratio.sort_values("avg_like_ratio", ascending=False)

tag_country_ratio.head(100)

                                     tag country avg_like_ratio
1046447                             AT&T      RU        11688.0
28269                 "AUDIENCE Network"      RU        11688.0
84503                        "Direct TV"      RU        11688.0
28219                              "ATT"      RU        11688.0
266505                         "U-Verse"      RU        11688.0
...                                  ...     ...            ...
393381           "dbs super 124 preview"      FR         2010.5
411057   "dragon ball super episode 124"      FR         2010.5
411109   "dragon ball super preview 124"      FR         2010.5
411058   "dragon ball super episode 125"      FR         2010.5
1112597                        ìì°ë¯¼      KR         1981.0

[100 rows x 3 columns]

# 11. For each (trending_date, country) pair, the video with the largest number of views

In [88]:
df["trending_date"] = pd.to_datetime(df["trending_date"], format="%y.%d.%m")  


top_videos_daily = (
    df.loc[df.groupby(["trending_date", "country"])["views"].idxmax()]
    .reset_index(drop=True)
)

top_videos_daily.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio,publish_interval,tag_list
0,2Vv-BfVoq4g,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,ð§: https://ad.gt/yt-perfect\nð°: https://...,CA,77.513044,2017-11-09 11:00:00+00:00,"[edsheeran, ""ed sheeran"", ""acoustic"", ""live"", ..."
1,2Vv-BfVoq4g,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634127,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,ð§: https://ad.gt/yt-perfect\nð°: https://...,DE,77.512902,2017-11-09 11:00:00+00:00,"[edsheeran, ""ed sheeran"", ""acoustic"", ""live"", ..."
2,2Vv-BfVoq4g,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,"edsheeran""|""ed sheeran""|""acoustic""|""live""|""cov...",33523622,1634134,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,ð§: https://ad.gt/yt-perfect\nð°: https://...,FR,77.513234,2017-11-09 11:00:00+00:00,"[edsheeran"", ""ed sheeran"", ""acoustic"", ""live"",..."
3,2Vv-BfVoq4g,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634124,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,ð§: https://ad.gt/yt-perfect\nð°: https://...,GB,77.51276,2017-11-09 11:00:00+00:00,"[edsheeran, ""ed sheeran"", ""acoustic"", ""live"", ..."
4,ePO5M5DE01I,2017-11-14,Tiger Zinda Hai | Official Trailer | Salman Kh...,YRF,1,2017-11-07 06:01:50+00:00,"Tiger Zinda Hai Trailer|""Tiger Zinda Hai Offic...",35885754,829362,61195,101117,https://i.ytimg.com/vi/ePO5M5DE01I/default.jpg,False,False,False,Stay updated! ð Subscribe Now: https://goo....,IN,13.552774,2017-11-07 06:00:00+00:00,"[Tiger Zinda Hai Trailer, ""Tiger Zinda Hai Off..."

# 12. Divide trending_date into three columns: year, month, day

In [89]:
df["year"] = df["trending_date"].dt.year
df["month"] = df["trending_date"].dt.month
df["day"] = df["trending_date"].dt.day

df[["trending_date", "year", "month", "day"]].head()

  trending_date  year  month  day
0    2017-11-14  2017     11   14
1    2017-11-14  2017     11   14
2    2017-11-14  2017     11   14
3    2017-11-14  2017     11   14
4    2017-11-14  2017     11   14

# 13. For each (month, country) pair, the video with the largest number of views

In [90]:
idx = df.groupby(["month", "country"])["views"].idxmax()


top_videos_month = df.loc[idx]


top_videos_month = top_videos_month.sort_values(["country", "month"])


top_videos_month.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,ratings_disabled,video_error_or_removed,description,country,like_ratio,publish_interval,tag_list,year,month,day
10994,LsoLEjrDogU,2018-01-09,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,10,2018-01-04 04:49:43+00:00,"Bruno Mars|""Finesse""|""Cardi B""|""Finesse Remix""...",43067983,1717177,61567,...,False,False,Finesse (Remix) Feat. Cardi B Available Now: h...,CA,27.891192,2018-01-04 04:40:00+00:00,"[Bruno Mars, ""Finesse"", ""Cardi B"", ""Finesse Re...",2018,1,9
19641,xpVfcZ0ZcFM,2018-02-24,Drake - Godâs Plan,DrakeVEVO,10,2018-02-17 05:00:01+00:00,"Drake new music|""Drake Gods Plan""|""Drake Godâ...",47362934,2469057,31843,...,False,False,Godâs Plan (Official Video)\n\nSong Availabl...,CA,77.538454,2018-02-17 05:00:00+00:00,"[Drake new music, ""Drake Gods Plan"", ""Drake Go...",2018,2,24
21576,_I_D_8Z4sJE,2018-03-06,Nicky Jam x J. Balvin - X (EQUIS) | Video Ofic...,NickyJamTV,10,2018-03-02 05:00:19+00:00,"Bad Bunny|""Amorfoda""|""Dura""|""Daddy Yankee""|""Oz...",61163906,629164,23851,...,False,False,Disponible en tu plataforma preferida:\nhttps:...,CA,26.378936,2018-03-02 05:00:00+00:00,"[Bad Bunny, ""Amorfoda"", ""Dura"", ""Daddy Yankee""...",2018,3,6
31137,u9Mv98Gr5pY,2018-04-30,VENOM - Official Trailer (HD),Sony Pictures Entertainment,24,2018-04-24 03:45:03+00:00,"Venom|""Venom Movie""|""Venom (2018)""|""Marvel""|""M...",53071887,1243479,44414,...,False,False,We Are #Venom. 10.5.18\n\nOne of Marvel's most...,CA,27.997456,2018-04-24 03:40:00+00:00,"[Venom, ""Venom Movie"", ""Venom (2018)"", ""Marvel...",2018,4,30
33630,VYOjWnS4cMY,2018-05-13,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,10,2018-05-06 04:00:07+00:00,"Childish Gambino|""Rap""|""This Is America""|""mcDJ...",98938809,3037318,161813,...,False,False,âThis is Americaâ by Childish Gambino http...,CA,18.770544,2018-05-06 04:00:00+00:00,"[Childish Gambino, ""Rap"", ""This Is America"", ""...",2018,5,13

# 14. Read all json files with the video categories

In [99]:
import json


category_files = glob.glob(r"trendingYT\*_category_id.json")  
category_list = []


for file in category_files:
    country = os.path.basename(file).split("_")[0].upper()  
    
    with open(file, encoding="utf-8") as f:
        data = json.load(f)
    

    temp_df = pd.DataFrame([{
        "category_id": int(item["id"]),
        "category_title": item["snippet"]["title"],
        "country": country
    } for item in data.get("items", [])])
    
    category_list.append(temp_df)


categories_df = pd.concat(category_list, ignore_index=True)


categories_df.head()

   category_id    category_title country
0            1  Film & Animation      CA
1            2  Autos & Vehicles      CA
2           10             Music      CA
3           15    Pets & Animals      CA
4           17            Sports      CA

# 15. For each country, determine how many videos have a category that is not assignable.

In [98]:

df_cat = df.merge(
    categories_df,
    on=["country", "category_id"],
    how="left"  
)


df_cat["category_title"] = df_cat["category_title"].fillna("Not assignable")


not_assignable_counts = (
    df_cat[df_cat["category_title"] == "Not assignable"]
    .groupby("country")["video_id"]
    .count()
    .to_dict()
)

not_assignable_counts

{'CA': 69,
 'DE': 228,
 'FR': 85,
 'GB': 90,
 'IN': 41,
 'JP': 18,
 'KR': 280,
 'MX': 149,
 'RU': 1301}